export default {
    booking_date:'Fecha de reserva',
    trip_start_time:'Hora de inicio del viaje',
    trip_end_time:'Hora de finalización del viaje',
    customer_name:'Nombre de usuario',
    car_type:'Tipo de vehículo',
    vehicle_no:'Placa de vehículo',
    pickup_address:'Dirección de recojo',
    drop_address:'Dirección destino',
    assign_driver:'Asignar conductor',
    booking_status:'Estado de la reserva',
    trip_cost:'Costo del viaje',
    discount_ammount:'Importe de descuento',
    payment_status:'Estado de pago',
    payment_mode:'Modo de pago',
    booking_text:'Reservas',
    image:'Imagen',
    name:'Nombre',
    rate_per_km:'Tarifa por kilómetro',
    rate_per_hour:'Tarifa por hora',
    min_fare: 'Tarifa mínima',
    convenience_fee:'Tarifa extra',
    convenience_fee_percent:'Porcentaje de tarifa extra',
    today_text:'Hoy',
    gross_earning:'Ingresos completos',
    admin_convenience_fee:'Nuestra ganancia',
    this_month_text:'Mes',
    total:'Total',
    real_time_driver_section_text:'Conductores Tiempo real',
    allow_location:'Permitir ubicación en tiempo real',
    sign_in:'Registrarse',
    email_address:'Email',
    password:'Contraseña',
    sign_in_error:'Error de inicio de sesión. Por favor revise su correo electrónico y contraseña.',
    device_type:'Tipo de dispositivo',
    user_type:'Tipo de usuario',
    title:'Título',
    body:'Cuerpo',
    push_notification_title:'Push Notifications',
    promo_name:'Nombre promoción',
    description:'Descripción',
    promo_type:'Tipo de promoción',
    promo_discount_value:'Valor de descuento promocional',
    max_limit:'Valor límite máximo',
    min_limit:'Recuento mínimo de pedidos',
    start_date:'Fecha de inicio (dd/mm/yyyy)',
    end_date:'Fecha final (dd/mm/yyyy)',
    promo_usage:'Límite de uso promocional',
    promo_used_by:'Promo utilizada por',
    promo_offer:'Promo y ofertas',
    refferal_bonus:'Bono de recomendación',
    submit:'Enviar',
    update_failed:'Actualización fallida',
    first_name:'Nombre',
    last_name:'Apellido',
    email:'Email',
    mobile:'Celular',
    profile_image:'Imagen de perfil',
    vehicle_model:'Modelo de vehículo',
    account_approve:'Cuenta aprobada',
    driver_active:'Estado activo del conductor',
    lisence_image:'Imagen de licencia',
    vehicle_number:'Placa de vehículo',
    wallet_balance:'Saldo de billetera',
    signup_via_refferal:'Registrarse a través de referencia',
    refferal_id:'ID de referencia',
    all_user:'Todos los usuarios',
    notification_sent:'Notificaciones enviadas.',
    notification_sent_failed:'Envío de notificaciones fallido.',
    no_user_match:'No hay usuarios que coincidan',
    no_user_matching:'No se encontraron usuarios que coincidan con su selección.',
    dashboard_text:'Panel de control',
    user:'Usuario',
    booking_history:'Historial de reservas',
    promo:'Promociones',
    logout:'Cerrar sesión',
    driver_earning:'Historial de ganancias del conductor',
    earning_amount:'Cantidad de ganancia',
    driver_name:'Nombre del conductor',
    driver_image:'Imagen del conductor',
    months:'Meses',
    year:'Años',
    vehicle_type:'Tipo de vehículo',
    lisence_no:'Número de licencia',
    booking_discount_earning:'Descuento de reserva',
    trip_cost_driver_share:'Costo del viaje/Conductor compartido',
    Gross_trip_cost:"Costo total de viaje",
    Discounts:"Descuentos",
    Customer_paid:"Cliente pagado",
    Profit:"Beneficio (Costo pagado - Costo del viaje)",
    earning_reports:'Informes de ganancias',
    cash_payment_amount:'Cantidad de pago en efectivo',
    card_payment_amount:'Monto de pago con tarjeta',
    wallet_payment_amount:'Monto de pago de billetera',
    payment_getway:'Pasarela de pago'
}